#!/usr/bin/env php
<?php

chdir(__DIR__);

$option = getopt('', ['help']);

if ($argc <= 1)
{
    showHelp();
}
else
{
    if (isset($option['help']))
    {
        showHelp();
    }

    switch (strtolower($argv[1]))
    {
        case 'test':
            echo "\033[32mTest\033[0m" . PHP_EOL;
            break;

        case 'sass2css':
        case 'scss2css':
        case 'sasstocss':
        case 'scsstocss':
        case 'sass':
        case 'scss':
        case 'css':
            echo `php tools/sass2css.php`;
            break;

        case 'dumpautoload':
        case 'dump':
        case 'autoload':
        case 'classmap':
        case 'autoloadmap':
        case 'autoloadclassmap':
            echo `php tools/dumpAutoload.php`;
            break;

        default:
            showHelp();
            break;
    }
}

exit(0);


/*
| Helper functions
*/

/**
 * Show usage help.
 *
 * @return void
 */
function showHelp()
{
    $myName = basename(__FILE__);
    echo "Usage:\n";
    echo sprintf("    %s \033[32m{tool name}\033[0m\n", $myName);
    echo PHP_EOL;
    echo "    Tool names:\n";
    echo PHP_EOL;
    echo sprintf("     * %s\n", 'Convert SASS/SCSS to CSS:');
    echo sprintf("       \033[33m%s\033[0m\n", 'sass2css');
    echo sprintf("       \033[33m%s\033[0m\n", 'scss2css');
    echo sprintf("       \033[33m%s\033[0m\n", 'sasstocss');
    echo sprintf("       \033[33m%s\033[0m\n", 'scsstocss');
    echo sprintf("       \033[33m%s\033[0m\n", 'sass');
    echo sprintf("       \033[33m%s\033[0m\n", 'scss');
    echo sprintf("       \033[33m%s\033[0m\n", 'css');
    echo PHP_EOL;
    echo sprintf("     * %s\n", 'Dump autoload classes map:');
    echo sprintf("       \033[33m%s\033[0m\n", 'dumpautoload');
    echo sprintf("       \033[33m%s\033[0m\n", 'dump');
    echo sprintf("       \033[33m%s\033[0m\n", 'autoload');
    echo sprintf("       \033[33m%s\033[0m\n", 'classmap');
    echo sprintf("       \033[33m%s\033[0m\n", 'autoloadmap');
    echo sprintf("       \033[33m%s\033[0m\n", 'autoloadclassmap');
    exit(0);
}
